---
# Unified service orchestration playbook
# Usage:
#   ansible-playbook -i inventory/hosts orchestrate.yml -e service_action=start
#   ansible-playbook -i inventory/hosts orchestrate.yml -e service_action=stop
#   ansible-playbook -i inventory/hosts orchestrate.yml -e service_action=status
#
# This playbook routes to the appropriate workflow based on service_action:
# - start: Routes to playbooks/appname_start.yml (forward order: foo -> bar -> elephant)
# - stop: Routes to playbooks/appname_stop.yml (reverse order: elephant -> bar -> foo)
# - status: Routes to playbooks/appname_status.yml (forward order with workflow reporting)

- name: "Validate service action"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: "Check service_action is valid"
      ansible.builtin.assert:
        that:
          - service_action is defined
          - service_action in ['start', 'stop', 'status']
        fail_msg: "service_action must be one of: start, stop, status. Got: {{ service_action | default('undefined') }}"
        success_msg: "Service action validated: {{ service_action }}"

- name: "Route to start workflow"
  ansible.builtin.import_playbook: playbooks/appname_start.yml
  when: service_action == 'start'

- name: "Route to stop workflow"
  ansible.builtin.import_playbook: playbooks/appname_stop.yml
  when: service_action == 'stop'

- name: "Route to status workflow"
  ansible.builtin.import_playbook: playbooks/appname_status.yml
  when: service_action == 'status'
