---
# Unified service orchestration playbook
# Usage:
#   ansible-playbook -i inventory/hosts orchestrate.yml -e service_action=start
#   ansible-playbook -i inventory/hosts orchestrate.yml -e service_action=stop
#   ansible-playbook -i inventory/hosts orchestrate.yml -e service_action=status
#
# Services are processed in order: foo -> bar -> elephant

- name: "Foo service - {{ service_action | default('status') | capitalize }}"
  hosts: foo_servers
  gather_facts: false
  vars_files:
    - vars/foo.yml
  vars:
    cal_role_service_action: "{{ service_action | default('status') }}"
  roles:
    - cal_role

- name: "Bar service - {{ service_action | default('status') | capitalize }}"
  hosts: bar_servers
  gather_facts: false
  vars_files:
    - vars/bar.yml
  vars:
    cal_role_service_action: "{{ service_action | default('status') }}"
  roles:
    - cal_role

- name: "Elephant service - {{ service_action | default('status') | capitalize }}"
  hosts: elephant_servers
  gather_facts: false
  vars_files:
    - vars/elephant.yml
  vars:
    cal_role_service_action: "{{ service_action | default('status') }}"
  roles:
    - cal_role
