---
- name: Stop service with fallback kill
  hosts: localhost
  gather_facts: false

  vars:
    # Service script configuration
    service_script: "/scripts/foo.sh"
    stop_check_string: "stopping"
    stopped_check_string: "stopped"

    # Process identification for kill operation
    process_identifier: "COMPONENT=foo"

    # Timing configuration
    wait_seconds: 10
    post_kill_wait_seconds: 3

    # Return code configuration (for scripts with non-standard RC behavior)
    stop_check_rc: true                # Whether to validate return code for stop command
    stop_expect_zero_rc: true          # true = RC 0 is success, false = RC non-zero is success
    status_check_rc: true              # Whether to validate return code for status command
    status_expect_zero_rc: true        # true = RC 0 is success, false = RC non-zero is success

  tasks:
    - name: Stop service with block-rescue pattern
      block:
        - name: Stop the service
          ansible.builtin.command: "{{ service_script }} stop"
          register: stop_result
          changed_when: stop_result.rc == 0
          failed_when: >
            (stop_check_string not in stop_result.stdout) or
            (stop_check_rc and
              ((stop_expect_zero_rc and stop_result.rc != 0) or
               (not stop_expect_zero_rc and stop_result.rc == 0)))

        - name: "Wait for service to stop seconds - {{ wait_seconds }}"
          ansible.builtin.pause:
            seconds: "{{ wait_seconds }}"

        - name: Verify service has stopped
          ansible.builtin.command: "{{ service_script }} status"
          register: status_result
          changed_when: false
          failed_when: >
            (stopped_check_string not in status_result.stdout) or
            (status_check_rc and
              ((status_expect_zero_rc and status_result.rc != 0) or
               (not status_expect_zero_rc and status_result.rc == 0)))

        - name: Service stopped successfully
          ansible.builtin.debug:
            msg: "Service stopped successfully"

      rescue:
        - name: Service did not stop gracefully, killing process
          ansible.builtin.debug:
            msg: "Service failed to stop gracefully, attempting to kill process with identifier: {{ process_identifier }}"

        - name: Kill process by identifier
          ansible.builtin.command:
            cmd: "pkill -9 -f -- {{ process_identifier | quote }}"
          register: kill_result
          changed_when: kill_result.rc == 0
          failed_when: kill_result.rc not in [0, 1]

        - name: "Wait after kill seconds - {{ post_kill_wait_seconds }}"
          ansible.builtin.pause:
            seconds: "{{ post_kill_wait_seconds }}"

        - name: Verify process is dead
          ansible.builtin.command: "{{ service_script }} status"
          register: final_status
          changed_when: false
          failed_when: >
            (stopped_check_string not in final_status.stdout) or
            (status_check_rc and
              ((status_expect_zero_rc and final_status.rc != 0) or
               (not status_expect_zero_rc and final_status.rc == 0)))

        - name: Process killed successfully
          ansible.builtin.debug:
            msg: "Process killed successfully, service is now stopped"
